name: Release
on:
  push:
    tags:
      - main
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: "configuration-release.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Html Content
        id: html_content
        uses: vmgabriel/gha-content-html@0.2.0
        with:
          template: ".github/workflows/template.html"
          body: ${{steps.github_release.outputs.changelog}}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.github_release.outputs.changelog }}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send mail
        uses: dawidd6/action-send-mail@v2.3.0
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: New Features Into Project ${{repository}} -  ${{github.ref}}
          to: vmgabriel96@gmail.com
          from: Team Develop
          secure: true
          content_type: text/html
          ignore_cert: true
          body: ${{steps.html_content.outputs.html_data}}

