name: Release
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          initial_version: "v1.0.0"

      - name: Get Commit Message
        id: branch
        run: echo "${{ github.event.head_commit.message }}"
