name: Release
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2


      - name: "Get Latest Tag"
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          initial_version: "v1.1.0"

      # Load Private
      - name: "Checkout Private"
        uses: actions/checkout@v2
        with:
          repository: FithubLatam/ga-level-status
          ref: "main"
          ssh-key: ${{ secrets.SSH_KEY }}
          persist-credentials: true
          path: .github/actions/ga-level
      - name: "Run My Action"
        uses: ./.github/actions/ga-level
        id: level_status
        with:
          message_commit: "${{ github.event.head_commit.message }}"

      - uses: actions-ecosystem/action-bump-semver@v1
        if: steps.level_status.outputs.level
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: "${{ steps.level_status.outputs.level }}"

      - uses: actions-ecosystem/action-push-tag@v1
        if: contains('${{ steps.level_status.outputs.level }}', 'minor')
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: Minor Version'
