name: Release
on:
  push:
    branches:
      - 'main'


jobs:
  check_pr:
    name: "Check PR"
    runs-on: ubuntu-latest
    outputs:
      level: ${{ steps.level_status.outputs.level }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Checkout Private"
        uses: actions/checkout@v2
        with:
          repository: FithubLatam/ga-level-status
          ref: "main"
          ssh-key: ${{ secrets.SSH_KEY }}
          persist-credentials: true
          path: .github/actions/ga-level
      - name: "Run Level Status"
        uses: ./.github/actions/ga-level
        id: level_status
        with:
          message_commit: "${{ github.event.head_commit.message }}"
          default_level: ""

  release:
    name: "Release"
    if: needs.check_pr.outputs.level != ''
    needs: [check_pr]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Get Latest Tag"
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          initial_version: "v1.1.0"

      - name: "Get New Tag"
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: "${{ needs.check_pr.outputs.level }}"

      - name: "Get New Version"
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: New Version'

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: "configuration-release.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Create Release"
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
          release_name: ${{ steps.bump-semver.outputs.new_version }}
          body: ${{steps.build_changelog.outputs.changelog }}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Send Mail"
        uses: dawidd6/action-send-mail@v2.3.0
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: New Features Into Project ${{ steps.build_changelog.outputs.repo }}
          to: vmgabriel96@gmail.com
          from: Team Develop
          secure: true
          content_type: text/html
          ignore_cert: true
          body: ${{ steps.build_changelog.outputs.changelog }}
          convert_markdown: true
